"""added war tables

Revision ID: 0f8ca2f05926
Revises: 86a9c01f2cdd
Create Date: 2025-02-19 02:33:38.049913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8ca2f05926'
down_revision = '86a9c01f2cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_member_id', sa.Integer(), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('destruction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_member_id'], ['clan_member.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_performance_attacks'), ['attacks'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_performance_clan_member_id'), ['clan_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_performance_destruction'), ['destruction'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_performance_stars'), ['stars'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_performance_war_id'), ['war_id'], unique=False)

    with op.batch_alter_table('clan_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_war_stars', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('averate_num_attacks', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_clan_member_average_war_stars'), ['average_war_stars'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_averate_num_attacks'), ['averate_num_attacks'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_war_preference'), ['war_preference'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_member_war_preference'))
        batch_op.drop_index(batch_op.f('ix_clan_member_averate_num_attacks'))
        batch_op.drop_index(batch_op.f('ix_clan_member_average_war_stars'))
        batch_op.drop_column('averate_num_attacks')
        batch_op.drop_column('average_war_stars')

    with op.batch_alter_table('war_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_performance_war_id'))
        batch_op.drop_index(batch_op.f('ix_war_performance_stars'))
        batch_op.drop_index(batch_op.f('ix_war_performance_destruction'))
        batch_op.drop_index(batch_op.f('ix_war_performance_clan_member_id'))
        batch_op.drop_index(batch_op.f('ix_war_performance_attacks'))

    op.drop_table('war_performance')
    # ### end Alembic commands ###
