"""clan member table

Revision ID: 86a9c01f2cdd
Revises: ccc83e9992a7
Create Date: 2025-02-19 00:20:19.904451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a9c01f2cdd'
down_revision = 'ccc83e9992a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=False),
    sa.Column('town_hall_level', sa.Integer(), nullable=False),
    sa.Column('war_preference', sa.Boolean(), nullable=False),
    sa.Column('clan_capital_contributions', sa.Integer(), nullable=False),
    sa.Column('attackWins', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clan_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_member_attackWins'), ['attackWins'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_clan_capital_contributions'), ['clan_capital_contributions'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_donations'), ['donations'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_town_hall_level'), ['town_hall_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_trophies'), ['trophies'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_member_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clan_tag', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_account_clan_tag'), ['clan_tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_clan_tag'))
        batch_op.drop_column('clan_tag')

    with op.batch_alter_table('clan_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_clan_member_trophies'))
        batch_op.drop_index(batch_op.f('ix_clan_member_town_hall_level'))
        batch_op.drop_index(batch_op.f('ix_clan_member_tag'))
        batch_op.drop_index(batch_op.f('ix_clan_member_role'))
        batch_op.drop_index(batch_op.f('ix_clan_member_name'))
        batch_op.drop_index(batch_op.f('ix_clan_member_donations'))
        batch_op.drop_index(batch_op.f('ix_clan_member_clan_capital_contributions'))
        batch_op.drop_index(batch_op.f('ix_clan_member_attackWins'))

    op.drop_table('clan_member')
    # ### end Alembic commands ###
